### ISSUE TITLE
上传图片

### ISSUE THREAD

**Issue by jinhongjie007** [lanceWan/larablog#1]
使用editor编辑器  上传图片缺少token  在哪里设置？

**Comment by lanceWan** [comment]
@jinhongjie007  token好像没有设置的地方，我是将这个上传的链接token验证取消了

**Comment by jinhongjie007** [comment]
参考了别人的做法  直接把token写在了链接里  你可以看看  我刚才试验成功了
`imageUploadURL : '/admin/posts/upload?_token=' + '{{ csrf_token() }}'`
另外有其他的联系方式吗？可以给个qq吗？

**Comment by lanceWan** [comment]
@jinhongjie007 额，我还忘了这种方式也是可以的，谢谢，get it
