### ISSUE TITLE
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

### ISSUE THREAD

**Issue by turtleliangzi** [lanceWan/larablog#2]
when i run composer install, there is a problem:[RuntimeException] The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
can you help me resolve this problem!

**Comment by turtleliangzi** [comment]
I found the awesome, because the file of .env do not have app_key

**Comment by lanceWan** [comment]
copy other project app_key to in .env file ,  this is Laravel5.3 bug @turtleliangzi

**Comment by turtleliangzi** [comment]
thanks, i have solve this problem!
